version: "3"

services:
  citus-db:
    container_name: "de-citus-db"
    image: citusdata/citus:11.1.5
    environment:
      POSTGRES_USER: citususer
      POSTGRES_PASSWORD: cituspass
      PGUSER: citususer
      PGPASSWORD: cituspass
    volumes:
      - citus-data-volume:/data/postgres
      - ./data/wh-db-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 25432:5432
  transformation-db:
    container_name: "de-database"
    image: postgres:15.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
    volumes:
      - transformation-data-volume:/data/postgres
    ports:
      - 15432:5432

networks:
  citus:
    driver: bridge
  transformation:
    driver: bridge

volumes:
  citus-data-volume:
  transformation-data-volume:
