@startuml Graph

scale 2

circle Publication
circle Author
circle Affiliation
circle Venue
circle ScientificDomain

Publication --> Author : published_by
Author --> Publication : author_of
Author -> Author : collaborates_with
Affiliation --> Author : employs
Author --> Affiliation : works_at
Publication --> Venue : published_in
Venue --> Publication : publishes
Venue --> ScientificDomain : covers
ScientificDomain --> Venue : covered_by
Publication --> ScientificDomain : belongs_to
ScientificDomain --> Publication : contains
Affiliation --> ScientificDomain : covers
ScientificDomain --> Affiliation : covered_by
Publication --> Publication : cites
Publication --> Publication : cited_by
Affiliation --> Venue : publishes_in
Venue --> Affiliation : publishes
Affiliation --> Affiliation : collaborates_with

@enduml